packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@heroui/shared-utils': true
  esbuild: true
  msw: true
  sharp: true
minimumReleaseAge: 0
minimumReleaseAgeExclude:
  - typescript
  - "@typescript/*"

overrides:
  "@react-aria/selection": 3.28.1
  storybook: 10.6.0
