-- Create favorite_livers table
CREATE TABLE IF NOT EXISTS public.favorite_livers (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references auth.users not null,
    liver_id text not null,
    unique(user_id, liver_id)
);

-- Enable RLS
ALTER TABLE public.favorite_livers ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Users can view their own favorites" 
ON public.favorite_livers FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own favorites" 
ON public.favorite_livers FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own favorites" 
ON public.favorite_livers FOR DELETE 
USING (auth.uid() = user_id);
